export const actionTypes = {
  FETCH_GENRES: 'FETCH_GENRES',
  GET_SELECTED_MOVIE: 'GET_SELECTED_MOVIE',
  CLOSE_SELECTED_MOVIE: 'CLOSE_SELECTED_MOVIE',
  GET_SELECTED_MOVIE_TRAILER: 'GET_SELECTED_MOVIE_TRAILER',
  SET_MENU_VISIBILITY: 'SET_MENU_VISIBILITY',
  FETCH_FAVORITE_MOVIES: 'FETCH_FAVORITE_MOVIES',
  FETCH_WATCHLIST_MOVIES: 'FETCH_WATCHLIST_MOVIES',
};
