export const actionTypes = {
  FETCH_GENRES: 'FETCH_GENRES',
  GET_SELECTED_MOVIE: 'GET_SELECTED_MOVIE',
  CLOSE_SELECTED_MOVIE: 'CLOSE_SELECTED_MOVIE',
  GET_SELECTED_MOVIE_TRAILER: 'GET_SELECTED_MOVIE_TRAILER',
};
