export const actionTypes = {
  FETCH_POPULAR_MOVIES_INITIAL: 'FETCH_POPULAR_MOVIES_INITIAL',
  FETCH_POPULAR_MOVIES_SUCCESFUL: 'FETCH_POPULAR_MOVIES_SUCCESFUL',
  FETCH_POPULAR_MOVIES_FAIL: 'FETCH_POPULAR_MOVIES_FAIL',
};
