export const actionTypes = {
  FETCH_POPULAR_FILMS_INITIAL: 'FETCH_POPULAR_FILMS_INITIAL',
  FETCH_POPULAR_FILMS_SUCCESFUL: 'FETCH_POPULAR_FILMS_SUCCESFUL',
  FETCH_POPULAR_FILMS_FAIL: 'FETCH_POPULAR_FILMS_FAIL',
};
