export const actionTypes = {
  FETCH_UPCOMING_MOVIES_INITIAL: 'FETCH_UPCOMING_MOVIES_INITIAL',
  FETCH_UPCOMING_MOVIES_SUCCESFUL: 'FETCH_UPCOMING_MOVIES_SUCCESFUL',
  FETCH_UPCOMING_MOVIES_FAIL: 'FETCH_UPCOMING_MOVIES_FAIL',
};
