export const actionTypes = {
  FETCH_QUERIED_FILMS_INITIAL: 'FETCH_QUERIED_FILMS_INITIAL',
  FETCH_QUERIED_FILMS_SUCCESFUL: 'FETCH_QUERIED_FILMS_SUCCESFUL',
  FETCH_QUERIED_FILMS_FAIL: 'FETCH_QUERIED_FILMS_FAIL',
  FETCH_RANDOM_MOVIE_SUCCESFUL: 'FETCH_RANDOM_MOVIE_SUCCESFUL',
  FETCH_RANDOM_MOVIE_FAIL: 'FETCH_RANDOM_MOVIE_FAIL',
};
