export const actionTypes = {
  FETCH_QUERIED_MOVIES_INITIAL: 'FETCH_QUERIED_MOVIES_INITIAL',
  FETCH_QUERIED_MOVIES_SUCCESFUL: 'FETCH_QUERIED_MOVIES_SUCCESFUL',
  FETCH_QUERIED_MOVIES_FAIL: 'FETCH_QUERIED_MOVIES_FAIL',
};
